/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problem5;

import java.util.Arrays;

/**
 * Survey window
 * @author bachle
 */
public class surveyWindow extends javax.swing.JFrame {

    /**
     * Creates new form surveyWindow
     */
    public surveyWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkBoxShooters = new javax.swing.JCheckBox();
        checkBoxFighters = new javax.swing.JCheckBox();
        checkBoxPlatformers = new javax.swing.JCheckBox();
        checkBoxStrategy = new javax.swing.JCheckBox();
        checkBoxRPG = new javax.swing.JCheckBox();
        checkBoxPuzzle = new javax.swing.JCheckBox();
        checkBoxArcade = new javax.swing.JCheckBox();
        checkBoxSports = new javax.swing.JCheckBox();
        checkBoxOther = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        comboBoxHours = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        textAreaGames = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel1.setText("Please answer the following survey.");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel2.setText("1. What types of games do you like playing (Check all that apply)");

        checkBoxShooters.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        checkBoxShooters.setText("Shooters");

        checkBoxFighters.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        checkBoxFighters.setText("Fighters");

        checkBoxPlatformers.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        checkBoxPlatformers.setText("Platformers");

        checkBoxStrategy.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        checkBoxStrategy.setText("Strategy");

        checkBoxRPG.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        checkBoxRPG.setText("RPG");

        checkBoxPuzzle.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        checkBoxPuzzle.setText("Puzzle");
        checkBoxPuzzle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPuzzleActionPerformed(evt);
            }
        });

        checkBoxArcade.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        checkBoxArcade.setText("Arcade");

        checkBoxSports.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        checkBoxSports.setText("Sports");
        checkBoxSports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSportsActionPerformed(evt);
            }
        });

        checkBoxOther.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        checkBoxOther.setText("Other");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel3.setText("2. How many hours per week do you spend gaming?");

        comboBoxHours.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        comboBoxHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< 5 hours", "< 10 hours", "< 15 hours", "15+ hours" }));
        comboBoxHours.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel4.setText("3. Enter a few games you're playing right now (Seperated by commas)");

        submitButton.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        textAreaGames.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkBoxPlatformers)
                                            .addComponent(checkBoxFighters)
                                            .addComponent(checkBoxShooters))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkBoxStrategy)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(checkBoxRPG)
                                                    .addComponent(checkBoxPuzzle))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(checkBoxSports))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(checkBoxOther))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(checkBoxArcade))))))
                                    .addComponent(jLabel3)
                                    .addComponent(comboBoxHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textAreaGames, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxShooters)
                    .addComponent(checkBoxStrategy)
                    .addComponent(checkBoxArcade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxFighters)
                    .addComponent(checkBoxRPG)
                    .addComponent(checkBoxSports))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxPlatformers)
                    .addComponent(checkBoxPuzzle)
                    .addComponent(checkBoxOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(comboBoxHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(textAreaGames, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxPuzzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPuzzleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPuzzleActionPerformed

    private void checkBoxSportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxSportsActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

    }//GEN-LAST:event_submitButtonActionPerformed

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        String filename = "results.txt";
        file.create(filename); //Creates a new file
        
        //Retrieves data from the current file
        int surveyCount = retrieve.surveyCount(filename);
        int[] question1 = retrieve.question1Data(filename);
        int[] question2 = retrieve.question2Data(filename); 
        String[] question3 = retrieve.question3Data(filename, surveyCount);
        
        //Updates the file
        file.update(filename, surveyCount, question1, question2, question3, getCheckBox(), getComboBox(), getTextArea());
    }//GEN-LAST:event_submitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(surveyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(surveyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(surveyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(surveyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new surveyWindow().setVisible(true);
            }
        });
    }

    /**
     *  Reads the checkboxes
     * @return  int array filled with 0s or 1s
     */
    public int[] getCheckBox() {
        boolean[] values = new boolean[9];

        values[0] = checkBoxShooters.isSelected();
        values[1] = checkBoxFighters.isSelected();
        values[2] = checkBoxPlatformers.isSelected();

        values[3] = checkBoxStrategy.isSelected();
        values[4] = checkBoxRPG.isSelected();
        values[5] = checkBoxPuzzle.isSelected();

        values[6] = checkBoxArcade.isSelected();
        values[7] = checkBoxSports.isSelected();
        values[8] = checkBoxSports.isSelected();

        int[] intValues = new int[9];
        for (int i = 0; i < values.length; i++) {
            if (values[i]) {
                intValues[i] = 1;
            } else {
                intValues[i] = 0;
            }
        }
        return intValues;
    }

    /**
     * Checks which box is selected
     *
     * @return Returns an array with integers
     */
    public int[] getComboBox() {
        int[] values = new int[4];
        Arrays.fill(values, 0);

        if (comboBoxHours.getSelectedItem().equals("< 5 hours")) {
            values[0] = 1;
        } 

        if (comboBoxHours.getSelectedItem().equals("< 10 hours")) {
            values[1] = 1;
        }
        
        if (comboBoxHours.getSelectedItem().equals("< 15 hours")) {
            values[2] = 1;
        }
        
        if (comboBoxHours.getSelectedItem().equals("15+ hours")) {
            values[3] = 1;
        } 
        return values;
    }

    /**
     * Gets text in textArea
     *
     * @return String
     */
    public String getTextArea() {
        return "- " + textAreaGames.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxArcade;
    private javax.swing.JCheckBox checkBoxFighters;
    private javax.swing.JCheckBox checkBoxOther;
    private javax.swing.JCheckBox checkBoxPlatformers;
    private javax.swing.JCheckBox checkBoxPuzzle;
    private javax.swing.JCheckBox checkBoxRPG;
    private javax.swing.JCheckBox checkBoxShooters;
    private javax.swing.JCheckBox checkBoxSports;
    private javax.swing.JCheckBox checkBoxStrategy;
    private javax.swing.JComboBox<String> comboBoxHours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField textAreaGames;
    // End of variables declaration//GEN-END:variables
}
